[[UDPipe]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2308d66faf31b4fcf883c582601bcbe681ee10e8"
os = "macos"

    [[UDPipe.download]]
    sha256 = "27e2ecb7435b4eb9701034721f58ca2acb965911fe08eef7c5f1941c605d4551"
    url = "https://github.com/peter-grajcar/UDPipe_Julia_Wrapper/releases/download/v0.1.0/UDPipe.v0.1.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[UDPipe]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f832b7891445242c3e6b76116d77ef72c3fa5673"
libc = "glibc"
os = "linux"

    [[UDPipe.download]]
    sha256 = "e6108849f441d7e13cf08797244bc916fa7725aa56b25ed55a380163bddee8c2"
    url = "https://github.com/peter-grajcar/UDPipe_Julia_Wrapper/releases/download/v0.1.0/UDPipe.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
