[[UDPipe]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2308d66faf31b4fcf883c582601bcbe681ee10e8"
os = "macos"

    [[UDPipe.download]]
    sha256 = "f9a1bf206009185434bb68171163b0488f161d19d253022f65b23c5fbf11563f"
    url = "https://github.com/peter-grajcar/UDPipe_Julia_Wrapper/releases/download/v0.1.0/UDPipe_Julia_Wrapper.v0.1.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[UDPipe]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f832b7891445242c3e6b76116d77ef72c3fa5673"
libc = "glibc"
os = "linux"

    [[UDPipe.download]]
    sha256 = "2d693027b09414f2f053f278e7a40f1e7fc5bb059bf6ddb623524abd7cb597f0"
    url = "https://github.com/peter-grajcar/UDPipe_Julia_Wrapper/releases/download/v0.1.0/UDPipe_Julia_Wrapper.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
